# Generated by Django 2.1.4 on 2018-12-19 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miasto',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
